services:
  - type: web
    name: smartshop-backend
    runtime: python
    buildCommand: "./backend/build.sh"
    startCommand: "cd backend && gunicorn smartshop_backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: smartshop-db
          property: connectionString

databases:
  - name: smartshop-db
    databaseName: smartshop
    user: smartshop
